### PR TITLE
aniston add collection

### PR DESCRIPTION
**Pull request by wer340**
hi owner please  take look this branch if you accepted by you  add your master branch good lock @wer340

### CODE REVIEW

**Comment by camel93** [comment]
hi camel i look your branch  
✔check emoji 
✔add beauty photo in bottom

**Comment by wer340** [comment]
> hi camel i look your branch ✔check emoji ✔add beauty photo in bottom

ok sir  complish ASAP

**Comment by wer340** [comment]
owner had acomplish term of your command take look again thanks💖

**Comment by camel93** [comment]
hi camel   

> owner had acomplish term of your command take look again thanks💖

all right  after check  this branch add to main a

**Pull request merged**
